version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: formosastay-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: formosastay
      POSTGRES_PASSWORD: passwordyeah!
      POSTGRES_DB: formosastay
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
